def calcPallPos1XY(nPosX,distX,nPosY,distY,nPezzo):

    # calcola posizione del prossimo pezzo sul pallet in X e Y dal primo pezzo della griglia (origine, ossia in basso a sinistra)

    # nPosX è il numero di colonne
    # nPosY è il numero di righe
    # distX è la distanza tra colonne
    # distY è la distanza tra righe

    posX = nPezzo%nPosX
    if(posX==0): posX = 4 end
    posY = ceil(nPezzo/nPosX)

    X=distX*(posX - 1)
    Y=distY*(posY - 1)
    xy=[X,Y]

    return xy
  
 end
